@startuml ConnectFour

class GameEngine {
    -players: IPlayer[]
    -gameBoard: IGameBoard
    +Run()
    -GetPlayerForTurn() : IPlayer
}

interface IPlayer {
    +Name: string
    +Number: int
    +GetNextMove(): int
}
class Player {
    #numberOfColumns: int
}
class HumanPlayer {
    -input: IInput
}
class ComputerPlayer
interface IInput
class ConsoleInput

interface IGameBoard {
    +PlaceToken(int, int) : bool
    +IsInWinningState(int): bool
    +ShowGameBoard()
}

class GameBoard {
    -gameBoardMatrix: int[][]
    -gameBoardViewer: IGameBoardViewer
    -rowIndexUpperBound: int
    -colIndexUpperBound: int
    -tokensInLineForAWin: int
    -CompensateForZeroBasedIndex(int): int
}

interface IGameBoardViewer {
    +ShowGameBoard(int[][], int, int)
}

class GameBoardViewer {
}

GameEngine "1" *-- "many" IPlayer

IPlayer <|.. Player

Player <|-- HumanPlayer
Player <|-- ComputerPlayer

HumanPlayer *-- IInput
IInput <|.. ConsoleInput

GameEngine "1" *-- "1" IGameBoard
IGameBoard <|.. GameBoard

GameBoard "1" *-- "1" IGameBoardViewer
IGameBoardViewer <|.. GameBoardViewer

@enduml